---
language: python

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      python: "2.7"

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Test Installation of Latest Version of Vagrant
  - ansible-playbook tests/test_latest_version.yml --connection local -vvi tests/inventory

  # Test Forcing Installation of a specific version
  - ansible-playbook tests/test_specific_version.yml --connection local -vvi tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
