---
language: python

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      python: "2.7"

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml --connection local -vvi tests/inventory --syntax-check

  # Test Role functionality
  - ansible-playbook tests/test.yml --connection local -vvi tests/inventory

  # Check Sysdig installed properly
  - vagrant --version

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
