---
- name: Download suitable installer package file
  get_url:
    url: "{{ vagrant_release_url }}/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_{{ ansible_architecture }}.deb"
    dest: "{{ vagrant_dest_path }}.deb"


- name: Remove current vagarant installation
  become: yes
  yum:
    name: vagrant
    state: absent
  when: vagrant_allow_downgrade


- name: Install Vagrant
  become: yes
  apt:
    deb: "{{ vagrant_dest_path }}.deb"
    state: present
